"""sermon transcript segments

Revision ID: 90e0b2579d19
Revises: a01ccbb964a2
Create Date: 2026-09-04 11:51:16.953250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e0b2579d19'
down_revision = 'a01ccbb964a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_segments', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.drop_column('transcript_segments')

    # ### end Alembic commands ###
