"""initial schema

Revision ID: a01ccbb964a2
Revises: 
Create Date: 2026-09-04 09:40:02.767938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a01ccbb964a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('churches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('last_crawled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('bot_name', sa.String(length=100), nullable=False),
    sa.Column('welcome_message', sa.String(length=500), nullable=False),
    sa.Column('primary_color', sa.String(length=7), nullable=False),
    sa.Column('church_city', sa.String(length=200), nullable=True),
    sa.Column('starter_questions', sa.Text(), nullable=True),
    sa.Column('bot_subtitle', sa.String(length=200), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=False),
    sa.Column('denomination', sa.String(length=40), nullable=False),
    sa.Column('denomination_profile_version', sa.String(length=40), nullable=True),
    sa.Column('denomination_updated_at', sa.DateTime(), nullable=True),
    sa.Column('local_practices', sa.Text(), nullable=True),
    sa.Column('statement_of_faith', sa.Text(), nullable=True),
    sa.Column('comms_enabled', sa.Boolean(), nullable=False),
    sa.Column('digest_last_sent_at', sa.DateTime(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('trial_ends_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=200), nullable=True),
    sa.Column('stripe_customer_id', sa.String(length=200), nullable=True),
    sa.Column('billing_exempt', sa.Boolean(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('trial_reminder_sent', sa.Boolean(), nullable=False),
    sa.Column('manual_payment_active', sa.Boolean(), nullable=False),
    sa.Column('manual_payment_note', sa.String(length=500), nullable=True),
    sa.Column('manual_payment_start', sa.Date(), nullable=True),
    sa.Column('manual_payment_expires', sa.Date(), nullable=True),
    sa.Column('manual_payment_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manual_payment_plan', sa.String(length=20), nullable=True),
    sa.Column('manual_payment_set_by', sa.String(length=200), nullable=True),
    sa.Column('stripe_invite_sent_at', sa.DateTime(), nullable=True),
    sa.Column('stripe_invite_resent_at', sa.DateTime(), nullable=True),
    sa.Column('warning_30_sent', sa.Boolean(), nullable=False),
    sa.Column('warning_7_sent', sa.Boolean(), nullable=False),
    sa.Column('expired_sent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('task', sa.String(length=30), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('vector', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_hash', 'model', 'task', name='uq_embedding_cache_key')
    )
    with op.batch_alter_table('embedding_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_embedding_cache_text_hash'), ['text_hash'], unique=False)

    op.create_table('system_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('church_calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('event_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('church_calendars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_church_calendars_church_id'), ['church_id'], unique=False)

    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversations_church_id'), ['church_id'], unique=False)

    op.create_table('crawled_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('crawled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'url', name='uq_church_url')
    )
    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawled_pages_church_id'), ['church_id'], unique=False)

    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=300), nullable=False),
    sa.Column('original_name', sa.String(length=300), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_church_id'), ['church_id'], unique=False)

    op.create_table('guest_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('interest_area', sa.String(length=100), nullable=True),
    sa.Column('opening_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('pco_person_id', sa.String(length=50), nullable=True),
    sa.Column('pco_synced_at', sa.DateTime(), nullable=True),
    sa.Column('pco_sync_error', sa.String(length=500), nullable=True),
    sa.Column('pco_sync_status', sa.String(length=20), nullable=True),
    sa.Column('pco_sync_attempts', sa.Integer(), nullable=False),
    sa.Column('pco_next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('pco_sync_started_at', sa.DateTime(), nullable=True),
    sa.Column('pco_email_synced', sa.Boolean(), nullable=False),
    sa.Column('pco_phone_synced', sa.Boolean(), nullable=False),
    sa.Column('pco_note_synced', sa.Boolean(), nullable=False),
    sa.Column('pco_workflow_synced', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_connections_church_id'), ['church_id'], unique=False)

    op.create_table('invites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invites_church_id'), ['church_id'], unique=False)

    op.create_table('knowledge_checklist_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'item_key', name='uq_church_knowledge_item')
    )
    with op.batch_alter_table('knowledge_checklist_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_checklist_states_church_id'), ['church_id'], unique=False)

    op.create_table('knowledge_pack_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('pack_key', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'pack_key', name='uq_church_knowledge_pack')
    )
    with op.batch_alter_table('knowledge_pack_states', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_pack_states_church_id'), ['church_id'], unique=False)

    op.create_table('qna_pairs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qna_pairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_qna_pairs_church_id'), ['church_id'], unique=False)

    op.create_table('sermon_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('channel_url', sa.String(length=500), nullable=False),
    sa.Column('channel_id', sa.String(length=100), nullable=False),
    sa.Column('channel_title', sa.String(length=200), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermon_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermon_sources_church_id'), ['church_id'], unique=True)

    op.create_table('text_snippets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('text_snippets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_text_snippets_church_id'), ['church_id'], unique=False)

    op.create_table('usage_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('surface', sa.String(length=20), nullable=False),
    sa.Column('model', sa.String(length=60), nullable=False),
    sa.Column('calls', sa.Integer(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('response_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('church_id', 'day', 'surface', 'model', name='uq_usage_daily_bucket')
    )
    with op.batch_alter_table('usage_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_daily_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_usage_daily_day'), ['day'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('reset_token', sa.String(length=100), nullable=True),
    sa.Column('reset_token_expires', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_church_id'), ['church_id'], unique=False)

    op.create_table('widget_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_conversations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_conversations_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_widget_conversations_session_id'), ['session_id'], unique=False)

    op.create_table('calendar_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['church_calendars.id'], ),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calendar_events_calendar_id'), ['calendar_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calendar_events_starts_at'), ['starts_at'], unique=False)

    op.create_table('comms_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('submitter_id', sa.Integer(), nullable=False),
    sa.Column('submitter_name', sa.String(length=200), nullable=False),
    sa.Column('ministry_department', sa.String(length=100), nullable=True),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('target_audience', sa.String(length=50), nullable=False),
    sa.Column('timeline', sa.String(length=50), nullable=False),
    sa.Column('deliverables', sa.JSON(), nullable=False),
    sa.Column('key_info_text', sa.Text(), nullable=True),
    sa.Column('special_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('triage_code', sa.String(length=20), nullable=True),
    sa.Column('production_tier', sa.Integer(), nullable=True),
    sa.Column('estimated_completion', sa.String(length=50), nullable=True),
    sa.Column('triage_explanation', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['submitter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comms_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comms_requests_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comms_requests_submitter_id'), ['submitter_id'], unique=False)

    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_conversation_id'), ['conversation_id'], unique=False)

    op.create_table('pco_connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('access_token', sa.String(length=1000), nullable=False),
    sa.Column('refresh_token', sa.String(length=1000), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(), nullable=False),
    sa.Column('organization_name', sa.String(length=200), nullable=True),
    sa.Column('auto_sync', sa.Boolean(), nullable=False),
    sa.Column('workflow_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_name', sa.String(length=200), nullable=True),
    sa.Column('connected_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['connected_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pco_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pco_connections_church_id'), ['church_id'], unique=True)

    op.create_table('sermons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('main_points', sa.Text(), nullable=True),
    sa.Column('scriptures', sa.String(length=500), nullable=True),
    sa.Column('series', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('ingested_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sermon_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermons_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sermons_source_id'), ['source_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sermons_video_id'), ['video_id'], unique=False)

    op.create_table('widget_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('widget_conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['widget_conversation_id'], ['widget_conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('widget_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_widget_messages_widget_conversation_id'), ['widget_conversation_id'], unique=False)

    op.create_table('answer_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('widget_message_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.String(length=20), nullable=False),
    sa.Column('reason', sa.String(length=40), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('corrected_answer', sa.Text(), nullable=True),
    sa.Column('qna_pair_id', sa.Integer(), nullable=True),
    sa.Column('resolved_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['qna_pair_id'], ['qna_pairs.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['widget_message_id'], ['widget_messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_feedback_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_feedback_widget_message_id'), ['widget_message_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_feedback_widget_message_id'))
        batch_op.drop_index(batch_op.f('ix_answer_feedback_church_id'))

    op.drop_table('answer_feedback')
    with op.batch_alter_table('widget_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_messages_widget_conversation_id'))

    op.drop_table('widget_messages')
    with op.batch_alter_table('sermons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermons_video_id'))
        batch_op.drop_index(batch_op.f('ix_sermons_source_id'))
        batch_op.drop_index(batch_op.f('ix_sermons_church_id'))

    op.drop_table('sermons')
    with op.batch_alter_table('pco_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pco_connections_church_id'))

    op.drop_table('pco_connections')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_conversation_id'))

    op.drop_table('messages')
    with op.batch_alter_table('comms_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comms_requests_submitter_id'))
        batch_op.drop_index(batch_op.f('ix_comms_requests_church_id'))

    op.drop_table('comms_requests')
    with op.batch_alter_table('calendar_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_church_id'))
        batch_op.drop_index(batch_op.f('ix_calendar_events_calendar_id'))

    op.drop_table('calendar_events')
    with op.batch_alter_table('widget_conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_widget_conversations_session_id'))
        batch_op.drop_index(batch_op.f('ix_widget_conversations_church_id'))

    op.drop_table('widget_conversations')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_church_id'))

    op.drop_table('users')
    with op.batch_alter_table('usage_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_daily_day'))
        batch_op.drop_index(batch_op.f('ix_usage_daily_church_id'))

    op.drop_table('usage_daily')
    with op.batch_alter_table('text_snippets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_text_snippets_church_id'))

    op.drop_table('text_snippets')
    with op.batch_alter_table('sermon_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermon_sources_church_id'))

    op.drop_table('sermon_sources')
    with op.batch_alter_table('qna_pairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qna_pairs_church_id'))

    op.drop_table('qna_pairs')
    with op.batch_alter_table('knowledge_pack_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_pack_states_church_id'))

    op.drop_table('knowledge_pack_states')
    with op.batch_alter_table('knowledge_checklist_states', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_checklist_states_church_id'))

    op.drop_table('knowledge_checklist_states')
    with op.batch_alter_table('invites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invites_church_id'))

    op.drop_table('invites')
    with op.batch_alter_table('guest_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_connections_church_id'))

    op.drop_table('guest_connections')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_church_id'))

    op.drop_table('documents')
    with op.batch_alter_table('crawled_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawled_pages_church_id'))

    op.drop_table('crawled_pages')
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversations_church_id'))

    op.drop_table('conversations')
    with op.batch_alter_table('church_calendars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_church_calendars_church_id'))

    op.drop_table('church_calendars')
    op.drop_table('system_prompts')
    with op.batch_alter_table('embedding_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_embedding_cache_text_hash'))

    op.drop_table('embedding_cache')
    op.drop_table('churches')
    # ### end Alembic commands ###
