"""content profiles and sermon packets

Revision ID: dbfa384bb56f
Revises: 90e0b2579d19
Create Date: 2026-09-04 11:54:28.282314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbfa384bb56f'
down_revision = '90e0b2579d19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('voice_notes', sa.Text(), nullable=True),
    sa.Column('title_strategy', sa.String(length=40), nullable=True),
    sa.Column('platforms', sa.String(length=200), nullable=True),
    sa.Column('hashtags', sa.String(length=300), nullable=True),
    sa.Column('call_to_action', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('content_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_content_profiles_church_id'), ['church_id'], unique=True)

    op.create_table('sermon_packets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('church_id', sa.Integer(), nullable=False),
    sa.Column('sermon_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('emailed_at', sa.DateTime(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['church_id'], ['churches.id'], ),
    sa.ForeignKeyConstraint(['sermon_id'], ['sermons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sermon_packets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sermon_packets_church_id'), ['church_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sermon_packets_sermon_id'), ['sermon_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sermon_packets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sermon_packets_sermon_id'))
        batch_op.drop_index(batch_op.f('ix_sermon_packets_church_id'))

    op.drop_table('sermon_packets')
    with op.batch_alter_table('content_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_content_profiles_church_id'))

    op.drop_table('content_profiles')
    # ### end Alembic commands ###
